Add sorts & search to main page
manifoldmarkets/manifund pull request #11
Opened 2023-03-08 18:26 UTC by rachelweinberg12

2023-03-08 23:26 UTC, akrolsmir requested changes
The searching and sorting work great! Just a few comments on code cleanliness (and I left one comment in the Vercel preview too)

2023-03-08 23:26 UTC, akrolsmir commented on app/projects/all-projects-display.tsx
> +  const sortOptions = [
I assume TailwindUI provided this code with sortOptions? I think it's a bit strange to have ids for each sortOption, and might have suggested something like:

`type SortOption = 'percent funded' | 'number of comments' | ...
const options: SortOption[] = ['percent funded', 'number of comments', ...]`

And then use the option itself as the React iterator key.

This also has the benefit of strongly typing the options, instead of just assuming it's a string. Whenever we have an enum (that is, a variable that can be one of several but not infinitely many different values), it's good to use a typescript type for it instead of just saying 'string'!

2023-03-08 23:26 UTC, akrolsmir commented on app/projects/all-projects-display.tsx
> +  return projects.filter((project) => {
Small code cleanliness thing: since we're doing these toLowerCase() calls a lot, I might have created a small helper function:
```
const check = (field) => field.toLowerCase().includes(search)

return check(project.title) || check(project.description?.toString()) || ...
```

2023-03-08 23:26 UTC, akrolsmir commented on app/projects/all-projects-display.tsx
> +      project.description
Note that it's a little bit weird to just be stringifying project description, since this is actually a weird JSON blob. A person reading this code might not realize this, and it can cause odd behavior like the word "heading" surface every result because it's in the JSON blob 
![image](https://user-images.githubusercontent.com/856034/223873346-e7095329-89cd-4cb0-93e2-33194b34b076.png)

Ideally we'd use a function for converting these Tiptap descriptions into plain text strings and then searching over them; since we don't have that yet, for now I'd just leave a comment in the code summarizing this issue. It's good practice to leave code comments about weird edge cases/unusual behaviors, so other people who stumble across it later will benefit from your understanding!

2023-03-08 23:26 UTC, akrolsmir commented on app/projects/all-projects-display.tsx
> +      project.title.toLowerCase().includes(search.toLowerCase()) ||
Let's add blurb too?

2023-03-08 23:26 UTC, akrolsmir commented on app/projects/all-projects-display.tsx
> +      project.description
Actually, it seems description search is broken, since `project.description?.toString()` always spits out `[Object object]`.

You probably intended to use `JSON.stringify(project.description)` instead! It's one of those unfortunate corner cases in Javascript (I would agree that a json blob.toString() ought to produce what JSON.stringify does)

2023-03-08 23:26 UTC, akrolsmir commented on app/projects/all-projects-display.tsx
> +        a.bids.reduce((acc, bid) => acc + bid.amount, 0) / a.min_funding <
This is a bit of a code smell -- it would be cleaner to have a function `getPercentFunded(fullProject)` that would return this value.

2023-03-08 23:26 UTC, akrolsmir commented on db/database.types.ts
> -          created_at: string | null
Thanks for updating the database to guarantee that created_at is always non-null! It's super nice to have strong type guarantees enforced by our database schema :)

2023-03-08 23:26 UTC, akrolsmir commented on app/projects/all-projects-display.tsx
> +              <Listbox.Button className=" relative w-full cursor-default rounded-md bg-white py-1.5 pl-3 pr-10 text-left text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:outline-none foc
Hm, I'm noticing that a big part of the code complexity here is in the Listbox component code (from TailwindUI, I assume). Could we pull it out the Listbox and styles into its own file in `components/`?

2023-03-09 03:03 UTC, rachelweinberg12 commented on app/projects/all-projects-display.tsx
> +  const sortOptions = [
done

2023-03-09 03:03 UTC, rachelweinberg12 commented on app/projects/all-projects-display.tsx
> +  return projects.filter((project) => {
done

2023-03-09 03:03 UTC, rachelweinberg12 commented on app/projects/all-projects-display.tsx
> +      project.description
removed this search option

2023-03-09 03:03 UTC, rachelweinberg12 commented on app/projects/all-projects-display.tsx
> +      project.title.toLowerCase().includes(search.toLowerCase()) ||
done

2023-03-09 03:04 UTC, rachelweinberg12 commented on app/projects/all-projects-display.tsx
> +              <Listbox.Button className=" relative w-full cursor-default rounded-md bg-white py-1.5 pl-3 pr-10 text-left text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:outline-none foc
sectioned off that code into its own component but left it in the same file

2023-03-09 03:06 UTC, akrolsmir approved these changes
LGTM!!!

2023-03-09 03:06 UTC, merged